"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv
import environ
env = environ.Env()
environ.Env.read_env()
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!m9=h&k%*x23lk_jdo$#yhaiyhy(x%zx$(f04*e(w1-+&eyt4f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = ["*", "localhost", "127.0.0.1", "192.168.89.66", "192.168.89.74"]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",  
    "http://192.168.89.74:3000",  # ✅ تأكد من استخدام IP الـ Frontend الصحيح
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = ["*"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django_extensions',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken', 
    'Registration.apps.RegistrationConfig',
    'corsheaders',

]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # أو إذا كنت تستخدم JWT:
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',

    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=60),  # مدة صلاحية التوكن
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'AUTH_HEADER_TYPES': ('Bearer',),
}



CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


LOGIN_REDIRECT_URL = 'home'
AUTH_USER_MODEL = 'Registration.User'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    
   
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://192.168.89.74:3000",  # ✅ السماح بالـ Frontend
]




ROOT_URLCONF = 'project.urls'
# ALLOWED_HOSTS = ['localhost', '127.0.0.1']
CORS_ALLOW_ALL_ORIGINS = True




TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import os


# إعداد قاعدة البيانات باستخدام المتغيرات البيئية
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('PGDATABASE', 'gradeguide'),  # اسم قاعدة البيانات (default: gradeguide)
        'USER': os.getenv('PGUSER', 'postgres'),  # اسم المستخدم (default: postgres)
        'PASSWORD': os.getenv('PGPASSWORD', '123456'),  # كلمة المرور (default: 123456)
        'HOST': os.getenv('PGHOST', 'localhost'),  # الخادم (default: localhost)
        'PORT': os.getenv('PGPORT', '5432'),  # المنفذ (default: 5432)
    },
    
}
import os
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(default=os.getenv("DATABASE_URL"))
}





# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
# settings.py
from django.contrib.auth.password_validation import MinimumLengthValidator, CommonPasswordValidator

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
      
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# إعدادات البريد الإلكتروني
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'abdelrahmanganem122@gmail.com'  # بريدك الإلكتروني
EMAIL_HOST_PASSWORD = 'rvwc azsj blmf wzjx'   # كلمة المرور لبريدك الإلكتروني

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# الحد الأقصى لحجم الملف في الذاكرة (بالبايت) قبل استخدام الملفات المؤقتة
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760    # بلا حد معين (إزالة القيود)

# المسار المؤقت للملفات عند رفع ملفات كبيرة




CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
import os
from dotenv import load_dotenv

# تحميل المتغيرات من ملف .env
load_dotenv()

# الآن يمكنك الوصول إلى المتغيرات من البيئة
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
