# Generated by Django 5.1.2 on 2025-02-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
