# Generated by Django 5.1.2 on 2025-02-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_qna_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='is_correct',
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
