# Generated by Django 5.1.2 on 2025-02-21 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarCorrectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('corrected_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_corrections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
