# Generated by Django 5.1.2 on 2025-02-21 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_grammarcorrectionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarcorrectionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
