# Generated by Django 5.1.2 on 2025-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_alter_grammarcorrectionhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarityresult',
            name='similarity_score',
        ),
        migrations.AddField(
            model_name='similarityresult',
            name='sbert_similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='similarityresult',
            name='tfidf_similarity',
            field=models.FloatField(default=0.0),
        ),
    ]
