# Generated by Django 5.1.2 on 2025-02-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_remove_similarityresult_similarity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarityresult',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
