# Generated by Django 5.1.2 on 2025-02-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_similarityresult_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarityresult',
            name='url',
        ),
    ]
