# Generated by Django 5.1.2 on 2025-04-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_remove_similarityresult_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarization',
            name='sbert_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarization',
            name='tfidf_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
