# Generated by Django 5.1.2 on 2025-04-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0013_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
