# Generated by Django 5.1.2 on 2025-04-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0014_remove_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
