# Generated by Django 5.1.2 on 2025-04-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0015_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarcorrectionhistory',
            name='sbert_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
