# Generated by Django 5.1.2 on 2025-04-17 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0016_grammarcorrectionhistory_sbert_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityResultURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('extracted_text', models.TextField()),
                ('sbert_similarity', models.FloatField(default=0.0)),
                ('tfidf_similarity', models.FloatField(default=0.0)),
                ('common_words', models.TextField()),
                ('common_sentences', models.TextField()),
                ('common_paragraphs', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('similarity_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='Registration.similarityresult')),
            ],
        ),
    ]
