# Generated by Django 5.1.2 on 2025-04-18 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0018_answer_user_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
