# Generated by Django 5.1.2 on 2025-04-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0019_answer_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarization',
            name='tfidf_score',
        ),
    ]
