# Generated by Django 5.1.2 on 2025-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0020_remove_summarization_tfidf_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarcorrectionhistory',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='corrected/'),
        ),
    ]
