# Generated by Django 5.1.2 on 2025-05-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0021_grammarcorrectionhistory_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarcorrectionhistory',
            name='diff',
            field=models.TextField(blank=True, null=True),
        ),
    ]
